### ISSUE TITLE
Problems using nrf24-scanner.py

### ISSUE THREAD

**Issue by jmcastro00** [iamckn/mousejack_transmit#2]
I am trying to use nrf24-scanner.py to sniff packet of a drone Syma X5SC-1 with a wifi card in python3. But the script non start. Could you help me to write the correct script, that I can detect the drone on?.

I hope your answer.

Best regards,

**Comment by iamckn** [comment]
That's out of the scope of this project but you can find dedicated guides elsewhere - https://medium.com/@swalters/how-to-set-up-a-drone-vulnerability-testing-lab-db8f7c762663
